services:
  sos-scraper:
    build: .
    ports:
      - "8000:5000"
    environment:
      - SOS_SCRAPER_ENVIRONMENT=local
  motoserver:
    image: motoserver/moto:latest
    ports:
      - "3000:3000"
    environment:
      - MOTO_PORT=3000 # set moto listener port with env var